[profile.default]
src = 'contracts-forge'
out = 'out'
libs = ['node_modules', 'lib']
test = 'tests-forge'
cache_path  = 'cache_forge'

[rpc_endpoints]
soneiumMainnet = "https://rpc.soneium.org"

baseSepolia = "https://sepolia.base.org"

[etherscan]
soneiumMainnet = { key = "${BASE_API_KEY}", chain = 84532, url="https://soneium.blockscout.com/api/" }

baseSepolia = { key = "any", chain = 1868, url="https://api-sepolia.basescan.org/api" }
