[profile.default]
src = 'contracts-forge'
out = 'out'
libs = ['node_modules', 'lib']
test = 'tests-forge'
cache_path  = 'cache_forge'

[rpc_endpoints]
baseSepolia = "https://sepolia.base.org"

[etherscan]
baseSepolia = { key = "${BASE_API_KEY}", chain = 84532, url="https://api-sepolia.basescan.org/api" }
