[profile.default]
src = 'contracts-forge'
out = 'out'
libs = ['node_modules', 'lib']
test = 'tests-forge'
cache_path  = 'cache_forge'
evm_version = 'london'

[rpc_endpoints]
#Mainnets
abstract = "https://api.mainnet.abs.xyz"
apeChain = "https://apechain.drpc.org"
appChain = "https://rpc.appchain.xyz/http"
arbitrumOne = "https://arbitrum-one-rpc.publicnode.com"
avalanche = "https://avalanche-c-chain-rpc.publicnode.com"
b3 = "https://mainnet-rpc.b3.fun"
berachain = "https://berachain-rpc.publicnode.com"
bsc = "https://bsc-rpc.publicnode.com"
bob = "https://bob-mainnet.public.blastapi.io"
celo = "https://rpc.ankr.com/celo"
cronos = "https://cronos-evm-rpc.publicnode.com"
gravity = "https://rpc.ankr.com/gravity"
hashKey = "https://mainnet.hsk.xyz"
hemi = "https://rpc.hemi.network/rpc"
hyperEVM = "https://rpc.hypurrscan.io"
immutable = "https://rpc.immutable.com"
ink = "https://ink.drpc.org"
lisk = "https://lisk.drpc.org"
metalL2 = "https://rpc.metall2.com"
mint = "https://rpc.mintchain.io"

mode = "https://mode.drpc.org"
opMainnet = "https://optimism-rpc.publicnode.com"
pharosTestnet = "https://testnet.dplabs-internal.com" # no SD
plume = "https://rpc.plume.org" # RegLim
polygon = "https://polygon-bor-rpc.publicnode.com"
polynomial = "https://rpc.polynomial.fi" # RegLim
race = "https://racemainnet.io"
rari= "https://mainnet.rpc.rarichain.org" # no SD
redstone = "https://rpc.redstonechain.com"
sei = "https://sei.drpc.org"
shape = "https://mainnet.shape.network"
somnia = "https://dream-rpc.somnia.network"
sonic = "https://sonic-rpc.publicnode.com"
sophon = "https://rpc.sophon.xyz"
story = "https://rpc.ankr.com/story_mainnet"
superposition = "https://rpc.superposition.so" # RegLim
swellchain = "https://rpc.ankr.com/swell"
tac = "https://rpc.tac.build" # EIP-1559 trouble
unichain = "https://unichain-rpc.publicnode.com"
vana = "https://rpc.vana.org"
worldChain = "https://worldchain.drpc.org"
xrpl = "https://rpc.xrplevm.org/"
zetaChain = "https://zeta-chain.drpc.org"

soneiumMainnet = "https://rpc.ankr.com/celo"

#Testnets
basecamp = "https://rpc-campnetwork.xyz"
base-sepolia = "https://sepolia.base.org"
riseTestnet = "https://testnet.riselabs.xyz"
sahara = "https://scroll-sepolia.drpc.org"
scroll-sepolia = "https://scroll-sepolia.drpc.org"
optimism-sepolia = "https://optimism-sepolia.drpc.org"
xrpl-testnet = "https://rpc.testnet.xrplevm.org/"

[etherscan]
#Mainnets
abstract = { key = "${ETHERSCAN_API_KEY}", chain = 2741, url="https://api.abscan.org/v2/api" }
apeChain = { key = "anything", chain = 33139, url="https://apechain.calderaexplorer.xyz/api" }
appChain = { key = "anything", chain = 466, url="https://appchain.calderaexplorer.xyz/api" }
arbitrumOne = { key = "${ETHERSCAN_API_KEY}", chain = 42161, url="https://arbitrum.blockscout.com/api/" }
avalanche = { key = "anything", chain = 43114, url="https://api.avascan.info/v2/network/mainnet/evm/43114/etherscan/" }
b3 = { key = "anything", chain = 8333, url="https://b3.calderaexplorer.xyz/api" }
berachain = { key = "${ETHERSCAN_API_KEY}", chain = 80094, url="https://api.berascan.com/v2/api" }
bsc = { key = "${ETHERSCAN_API_KEY}", chain = 56, url="https://api.bscscan.com/v2/api" }
bob = { key = "anything", chain = 60808, url="https://explorer-bob-mainnet-0.t.conduit.xyz/api/" }
celo = { key = "anything", chain = 42220, url="https://celo.blockscout.com/api" }
cronos = { key = "${ETHERSCAN_API_KEY}", chain = 25, url="https://cronoscan.com/" }
gravity = { key = "anything", chain = 1625, url="https://explorer-gravity-mainnet-0.t.conduit.xyz/api/" }
hashKey = { key = "anything", chain = 177, url="https://hashkey.blockscout.com/api" }
hemi = { key = "anything", chain = 43111, url="https://explorer.hemi.xyz/api" }
hyperEVM = { key = "anything", chain = 999, url="https://www.hyperscan.com/api" }
immutable = { key = "anything", chain = 13371, url="https://explorer.immutable.com/api" }
ink = { key = "anything", chain = 57073, url="https://explorer.inkonchain.com/api" }
lisk = { key = "anything", chain = 1135, url="https://blockscout.lisk.com/api" }
metalL2 = { key = "anything", chain = 169, url="https://explorer-metal-mainnet-0.t.conduit.xyz/api/" }
mint = { key = "anything", chain = 1750, url="https://explorer-mint-mainnet-0.t.conduit.xyz/api/" }

mode = { key = "anything", chain = 34443, url="https://explorer-mode-mainnet-0.t.conduit.xyz/api" }
opMainnet = { key = "anything", chain = 10, url="https://optimism.blockscout.com/api" }
pharosTestnet = { key = "anything", chain = 688688, url="https://testnet.pharosscan.xyz/api/" }
plume = { key = "anything", chain = 98866, url="https://explorer-plume-mainnet-0.t.conduit.xyz/api/" }
polygon = { key = "${ETHERSCAN_API_KEY}", chain = 137, url="https://v2.polygonscan.com/v2/api" }
polynomial = { key = "anything", chain = 8008, url="https://api.routescan.io/v2/network/mainnet/evm/8008/etherscan/api/" }
race = { key = "anything", chain = 6805, url="https://racescan.io/api" }
rari= { key = "anything", chain = 1380012617, url="https://rari.calderaexplorer.xyz/api" }
redstone = { key = "anything", chain = 690, url="https://explorer.redstone.xyz/api" }
sei = { key = "anything", chain = 1329, url="https://sei.blockscout.com/api/" }
shape = { key = "anything", chain = 360, url="https://shapescan.xyz/api" }
somnia = { key = "anything", chain = 50312, url="https://somnia.w3us.site/api/" }
sonic = { key = "${ETHERSCAN_API_KEY}", chain = 146, url="https://v2.sonicscan.org/v2/api" }
sophon = { key = "${ETHERSCAN_API_KEY}", chain = 50104, url="https://v2.sophscan.xyz/v2/api" }
story = { key = "anything", chain = 1514, url="https://www.storyscan.io/api/" }
superposition = { key = "anything", chain = 55244, url="https://explorer-superposition-1v9rjalnat.t.conduit.xyz/api/" }
swellchain = { key = "anything", chain = 1923, url="https://explorer.swellnetwork.io:443/api" }
tac = { key = "anything", chain = 239, url="https://explorer.tac.build/api" }
unichain = { key = "anything", chain = 130, url="https://unichain.blockscout.com/api" }
vana = { key = "anything", chain = 1480, url="https://vanascan.io/api" }
worldChain = { key = "${ETHERSCAN_API_KEY}", chain = 480, url="https://v2.worldscan.org/v2/api" }
xrpl = { key = "anything", chain = 1440000, url="https://explorer.xrplevm.org/api/" }
zetaChain = { key = "anything", chain = 7000, url="https://zetachain.blockscout.com/api" }

soneiumMainnet = { key = "${BASE_API_KEY}", chain = 84532, url="https://soneium.blockscout.com/api/" }

#Testnets
basecamp = { key = "any", chain = 123420001114, url="https://camp-network-testnet.blockscout.com/api" }
base-sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532, url="https://api-sepolia.basescan.org/api" }
riseTestnet = { key = "anything", chain = 11155931, url="https://explorer.testnet.riselabs.xyz/api" }
sahara = { key = "anything", chain = 3132023, url="https://testnet-explorer.saharalabs.ai/api" }
scroll-sepolia = { key = "anything", chain = 534351, url="https://scroll-sepolia.blockscout.com/api" }
optimism-sepolia = { key = "anything", chain = 11155420, url="https://testnet-explorer.optimism.io/api" }
xrpl-testnet = { key = "anything", chain = 1449000, url="https://explorer.testnet.xrplevm.org/api/" }
